"""add password column field.

Revision ID: 416f55a96262
Revises: 5245a1c394f3
Create Date: 2026-07-26 16:35:23.580574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '416f55a96262'
down_revision = '5245a1c394f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
